import React, { useState, useEffect, useRef } from "react";
import PropTypes from "prop-types";
import OrderService from "../../../services/OrderService";
import {
  Download,
  Share2,
  Printer,
  Mail,
  MessageSquare,
  X,
  Loader2,
  CheckCircle,
  AlertCircle,
  FileText,
  Calendar,
  User,
  Building,
  DollarSign,
  Percent,
  Clock,
  ChevronRight,
  Copy,
  Check,
  Smartphone,
  Paperclip,
  Zap,
  Shield,
  BarChart
} from "lucide-react";

const OrderInvoice = ({ onClose, order }) => {
  const [orderData, setOrderData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [showShareModal, setShowShareModal] = useState(false);
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);
  const [copiedField, setCopiedField] = useState(null);
  const [activeTab, setActiveTab] = useState("preview");
  const invoiceRef = useRef(null);

  useEffect(() => {
    const fetchOrderDetails = async () => {
      try {
        setLoading(true);
        if (typeof order === "string" || typeof order === "number") {
          const data = await OrderService.getOrderById(order);
          setOrderData(data);
        } else if (order && typeof order === "object") {
          setOrderData(order);
        }
      } catch (err) {
        console.error("Failed to fetch order details:", err);
        setError("Failed to load order details. Please try again.");
      } finally {
        setLoading(false);
      }
    };

    if (order) {
      fetchOrderDetails();
    }
  }, [order]);

  // Helper functions for formatting
  const formatDate = (dateString) => {
    if (!dateString) return "N/A";
    const date = new Date(dateString);
    return date.toLocaleDateString("en-US", {
      weekday: 'short',
      day: "numeric",
      month: "short",
      year: "numeric",
    });
  };

  const formatDateTime = (dateString) => {
    if (!dateString) return "N/A";
    const date = new Date(dateString);
    return date.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const formatAmount = (amount) => {
    if (!amount && amount !== 0) return "₦0.00";
    return `₦${Number(amount).toLocaleString()}`;
  };

  const calculateDueDate = (issuedDate, daysToAdd = 12) => {
    if (!issuedDate) return "N/A";
    const date = new Date(issuedDate);
    date.setDate(date.getDate() + daysToAdd);
    return formatDate(date.toISOString());
  };

  const calculateVAT = (amount, vatRate = 0.075) => {
    return Number(amount) * vatRate;
  };

  const copyToClipboard = async (text, fieldName) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedField(fieldName);
      setTimeout(() => setCopiedField(null), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  // PDF Generation Function
  const generatePDF = async () => {
    setIsGeneratingPDF(true);
    try {
      const html2canvas = (await import("html2canvas")).default;
      const jsPDF = (await import("jspdf")).jsPDF;

      const element = invoiceRef.current;
      if (!element) return null;

      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        backgroundColor: "#ffffff",
        logging: false,
        onclone: (clonedDoc) => {
          const cloneElement = clonedDoc.querySelector('#invoice-content');
          if (cloneElement) {
            cloneElement.style.padding = '40px';
            cloneElement.style.backgroundColor = '#ffffff';
          }
        }
      });

      const imgData = canvas.toDataURL("image/png", 1.0);
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
        putOnlyUsedFonts: true,
        floatPrecision: 16
      });

      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      const ratio = Math.min((pdfWidth - 20) / imgWidth, (pdfHeight - 40) / imgHeight);
      const imgX = (pdfWidth - imgWidth * ratio) / 2;
      const imgY = 20;

      pdf.addImage(
        imgData,
        "PNG",
        imgX,
        imgY,
        imgWidth * ratio,
        imgHeight * ratio,
        undefined,
        'FAST'
      );

      // Add watermark
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text("Generated by Order Management System", pdfWidth / 2, pdfHeight - 10, { align: 'center' });

      return pdf;
    } catch (error) {
      console.error("Error generating PDF:", error);
      throw new Error("Failed to generate PDF. Please try again.");
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  // Download PDF
  const handleDownload = async () => {
    try {
      const pdf = await generatePDF();
      if (pdf) {
        const invoiceNumber = orderData.id
          ? `INV-${String(orderData.id).padStart(4, "0")}`
          : "INV-0000";
        pdf.save(`Invoice_${invoiceNumber}_${new Date().toISOString().split('T')[0]}.pdf`);
        
        // Show success notification
        showNotification("PDF downloaded successfully!", "success");
      }
    } catch (error) {
      showNotification(error.message, "error");
    }
  };

  // Print invoice
  const handlePrint = () => {
    const printContent = invoiceRef.current;
    if (!printContent) return;

    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Invoice ${orderData.id ? `INV-${String(orderData.id).padStart(4, "0")}` : ""}</title>
          <style>
            @media print {
              body { margin: 0; padding: 20px; }
              .no-print { display: none !important; }
            }
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
            .invoice-container { max-width: 800px; margin: 0 auto; }
          </style>
        </head>
        <body>
          <div class="invoice-container">
            ${printContent.innerHTML}
          </div>
          <script>
            window.onload = function() { window.print(); window.close(); }
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  // Share functionality
  const shareInvoice = async (method) => {
    try {
      const pdf = await generatePDF();
      if (!pdf) return;

      const invoiceNumber = orderData.id
        ? `INV-${String(orderData.id).padStart(4, "0")}`
        : "INV-0000";
      
      const pdfBlob = pdf.output("blob");
      const file = new File([pdfBlob], `Invoice_${invoiceNumber}.pdf`, {
        type: "application/pdf",
      });

      if (method === "email") {
        const subject = `Invoice ${invoiceNumber} - ${orderData.order_title || "Order"}`;
        const body = `Dear ${orderData.client_full_name || "Customer"},

Please find attached your invoice for order #${orderData.id}.

Invoice Details:
• Invoice Number: ${invoiceNumber}
• Order Title: ${orderData.order_title || "N/A"}
• Amount: ${formatAmount(orderData.order_price)}
• Date: ${formatDate(orderData.ordered_at || orderData.created_at)}

Thank you for your business!

Best regards,
${orderData.business_profile?.business_name || "Your Company"}`;

        const mailtoLink = `mailto:${orderData.client_email || ""}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
        window.open(mailtoLink);
      } else if (method === "whatsapp") {
        const text = `Hi ${orderData.client_full_name || "there"}! 👋

Your invoice is ready! 📄

*Invoice Details:*
📋 Invoice Number: ${invoiceNumber}
🛍️ Order: ${orderData.order_title || "N/A"}
💰 Amount: ${formatAmount(orderData.order_price)}
📅 Date: ${formatDate(orderData.ordered_at || orderData.created_at)}

Thank you for your business! 🙏`;

        const whatsappLink = `https://wa.me/${orderData.client_phone?.replace(/\D/g, '') || ""}?text=${encodeURIComponent(text)}`;
        window.open(whatsappLink, "_blank");
      }

      setShowShareModal(false);
      showNotification(`Invoice shared via ${method === "email" ? "Email" : "WhatsApp"}!`, "success");
    } catch (error) {
      showNotification("Failed to share invoice", "error");
    }
  };

  const showNotification = (message, type = "info") => {
    // Create notification element
    const notification = document.createElement("div");
    notification.className = `fixed top-4 right-4 px-6 py-3 rounded-lg shadow-lg z-50 animate-slideIn ${
      type === "success" ? "bg-emerald-500 text-white" :
      type === "error" ? "bg-red-500 text-white" :
      "bg-blue-500 text-white"
    }`;
    notification.innerHTML = `
      <div class="flex items-center gap-3">
        ${type === "success" ? '<CheckCircle size={20} />' : '<AlertCircle size={20} />'}
        <span>${message}</span>
      </div>
    `;
    document.body.appendChild(notification);
    setTimeout(() => {
      notification.classList.add("animate-slideOut");
      setTimeout(() => document.body.removeChild(notification), 300);
    }, 3000);
  };

  // Invoice data calculations
  const invoiceNumber = orderData?.id ? `#INV-${String(orderData.id).padStart(5, "0")}` : "#INV-00000";
  const subtotal = Number(orderData?.order_price || 0);
  const vat = calculateVAT(subtotal);
  const total = subtotal + vat;
  const paidAmount = Number(orderData?.total_paid || 0);
  const balanceDue = total - paidAmount;
  const paymentStatus = balanceDue <= 0 ? "Paid" : "Pending";

  if (loading) {
    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
        <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl overflow-hidden animate-fadeIn">
          <div className="p-8 flex flex-col items-center justify-center min-h-[400px]">
            <div className="relative">
              <div className="w-16 h-16 border-4 border-blue-100 border-t-blue-600 rounded-full animate-spin"></div>
              <FileText className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-blue-600" size={24} />
            </div>
            <h3 className="mt-6 text-lg font-semibold text-gray-900">Loading Invoice</h3>
            <p className="mt-2 text-gray-600">Preparing your invoice details...</p>
          </div>
        </div>
      </div>
    );
  }

  if (error || !orderData) {
    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
        <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md overflow-hidden animate-fadeIn">
          <div className="p-8">
            <div className="flex items-center justify-center w-12 h-12 bg-red-100 rounded-xl mx-auto mb-4">
              <AlertCircle className="text-red-600" size={24} />
            </div>
            <h3 className="text-xl font-bold text-gray-900 text-center mb-2">Unable to Load Invoice</h3>
            <p className="text-gray-600 text-center mb-6">{error || "Invoice data not available"}</p>
            <div className="flex gap-3">
              <button
                onClick={onClose}
                className="flex-1 px-4 py-3 border border-gray-300 text-gray-700 rounded-xl hover:bg-gray-50 transition-colors font-medium"
              >
                Close
              </button>
              <button
                onClick={() => window.location.reload()}
                className="flex-1 px-4 py-3 bg-blue-600 text-white rounded-xl hover:bg-blue-700 transition-colors font-medium"
              >
                Retry
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <>
      <div className="fixed inset-0 z-50 overflow-y-auto">
        <div className="flex min-h-screen items-center justify-center p-4">
          {/* Backdrop */}
          <div 
            className="fixed inset-0 bg-black/50 backdrop-blur-sm transition-opacity"
            onClick={onClose}
          />

          {/* Main Modal */}
          <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-6xl overflow-hidden animate-slideUp">
            {/* Header */}
            <div className="sticky top-0 z-10 bg-white border-b border-gray-200 px-6 py-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <div className="p-2 bg-blue-100 rounded-lg">
                    <FileText className="text-blue-600" size={24} />
                  </div>
                  <div>
                    <h2 className="text-xl font-bold text-gray-900">Invoice</h2>
                    <div className="flex items-center gap-3 mt-1">
                      <span className="inline-flex items-center gap-1 px-3 py-1 bg-gray-100 text-gray-700 rounded-full text-sm font-medium">
                        <span className="w-2 h-2 bg-blue-500 rounded-full"></span>
                        {invoiceNumber}
                      </span>
                      <span className={`inline-flex items-center gap-1 px-3 py-1 rounded-full text-sm font-medium ${
                        paymentStatus === "Paid" 
                          ? "bg-emerald-100 text-emerald-800" 
                          : "bg-amber-100 text-amber-800"
                      }`}>
                        {paymentStatus === "Paid" ? <CheckCircle size={12} /> : <Clock size={12} />}
                        {paymentStatus}
                      </span>
                    </div>
                  </div>
                </div>
                
                <div className="flex items-center gap-2">
                  <button
                    onClick={onClose}
                    className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
                  >
                    <X size={20} className="text-gray-500" />
                  </button>
                </div>
              </div>

              {/* Tabs */}
              <div className="flex border-b border-gray-200 mt-4 -mb-px">
                <button
                  className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors ${
                    activeTab === "preview"
                      ? "border-blue-600 text-blue-600"
                      : "border-transparent text-gray-500 hover:text-gray-700"
                  }`}
                  onClick={() => setActiveTab("preview")}
                >
                  Preview
                </button>
                <button
                  className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors ${
                    activeTab === "details"
                      ? "border-blue-600 text-blue-600"
                      : "border-transparent text-gray-500 hover:text-gray-700"
                  }`}
                  onClick={() => setActiveTab("details")}
                >
                  Details
                </button>
                <button
                  className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors ${
                    activeTab === "timeline"
                      ? "border-blue-600 text-blue-600"
                      : "border-transparent text-gray-500 hover:text-gray-700"
                  }`}
                  onClick={() => setActiveTab("timeline")}
                >
                  Timeline
                </button>
              </div>
            </div>

            {/* Content */}
            <div className="p-6">
              {activeTab === "preview" ? (
                <div className="grid lg:grid-cols-3 gap-6">
                  {/* Left Column - Invoice Preview */}
                  <div className="lg:col-span-2">
                    <div id="invoice-content" ref={invoiceRef} className="bg-white border border-gray-200 rounded-xl p-8 shadow-sm">
                      {/* Invoice Header */}
                      <div className="flex justify-between items-start mb-8 pb-6 border-b border-gray-200">
                        <div>
                          <div className="flex items-center gap-3 mb-2">
                            {orderData.business_profile?.logo_url ? (
                              <img
                                src={orderData.business_profile.logo_url}
                                alt="Business Logo"
                                className="w-10 h-10 object-contain rounded-lg"
                              />
                            ) : (
                              <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-blue-600 rounded-lg flex items-center justify-center">
                                <Building className="text-white" size={20} />
                              </div>
                            )}
                            <div>
                              <h1 className="text-2xl font-bold text-gray-900">INVOICE</h1>
                              <p className="text-sm text-gray-600">{invoiceNumber}</p>
                            </div>
                          </div>
                          <p className="text-gray-500 text-sm">Issued by {orderData.business_profile?.business_name || "Your Business"}</p>
                        </div>
                        <div className="text-right">
                          <div className="text-lg font-bold text-blue-600 mb-1">{formatAmount(total)}</div>
                          <div className={`px-3 py-1 rounded-full text-sm font-medium inline-block ${
                            paymentStatus === "Paid" 
                              ? "bg-emerald-100 text-emerald-800" 
                              : "bg-amber-100 text-amber-800"
                          }`}>
                            {paymentStatus}
                          </div>
                        </div>
                      </div>

                      {/* Invoice Details Grid */}
                      <div className="grid md:grid-cols-2 gap-8 mb-8">
                        <div>
                          <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">Bill From</h3>
                          <div className="space-y-2">
                            <p className="font-semibold text-gray-900">{orderData.business_profile?.business_name || "Your Business"}</p>
                            {orderData.business_profile?.business_email && (
                              <p className="text-gray-600">{orderData.business_profile.business_email}</p>
                            )}
                            {orderData.business_profile?.business_phone && (
                              <p className="text-gray-600">{orderData.business_profile.business_phone}</p>
                            )}
                            {orderData.business_profile?.address && (
                              <p className="text-gray-600 text-sm">{orderData.business_profile.address}</p>
                            )}
                          </div>
                        </div>
                        <div>
                          <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">Bill To</h3>
                          <div className="space-y-2">
                            <div className="flex items-center justify-between">
                              <p className="font-semibold text-gray-900">{orderData.client_full_name || "Customer"}</p>
                              <button
                                onClick={() => copyToClipboard(orderData.client_full_name, "clientName")}
                                className="p-1 hover:bg-gray-100 rounded"
                                title="Copy name"
                              >
                                {copiedField === "clientName" ? (
                                  <Check size={14} className="text-green-600" />
                                ) : (
                                  <Copy size={14} className="text-gray-400" />
                                )}
                              </button>
                            </div>
                            {orderData.client_email && (
                              <div className="flex items-center justify-between">
                                <p className="text-gray-600">{orderData.client_email}</p>
                                <button
                                  onClick={() => copyToClipboard(orderData.client_email, "clientEmail")}
                                  className="p-1 hover:bg-gray-100 rounded"
                                  title="Copy email"
                                >
                                  {copiedField === "clientEmail" ? (
                                    <Check size={14} className="text-green-600" />
                                  ) : (
                                    <Copy size={14} className="text-gray-400" />
                                  )}
                                </button>
                              </div>
                            )}
                            {orderData.client_phone && (
                              <div className="flex items-center justify-between">
                                <p className="text-gray-600">{orderData.client_phone}</p>
                                <button
                                  onClick={() => copyToClipboard(orderData.client_phone, "clientPhone")}
                                  className="p-1 hover:bg-gray-100 rounded"
                                  title="Copy phone"
                                >
                                  {copiedField === "clientPhone" ? (
                                    <Check size={14} className="text-green-600" />
                                  ) : (
                                    <Copy size={14} className="text-gray-400" />
                                  )}
                                </button>
                              </div>
                            )}
                          </div>
                        </div>
                      </div>

                      {/* Dates Section */}
                      <div className="grid grid-cols-3 gap-4 mb-8 p-4 bg-gray-50 rounded-lg">
                        <div>
                          <p className="text-sm text-gray-500 mb-1">Issue Date</p>
                          <p className="font-medium text-gray-900">{formatDate(orderData.ordered_at || orderData.created_at)}</p>
                        </div>
                        <div>
                          <p className="text-sm text-gray-500 mb-1">Due Date</p>
                          <p className="font-medium text-gray-900">{calculateDueDate(orderData.ordered_at || orderData.created_at)}</p>
                        </div>
                        <div>
                          <p className="text-sm text-gray-500 mb-1">Payment Terms</p>
                          <p className="font-medium text-gray-900">12 days</p>
                        </div>
                      </div>

                      {/* Order Items */}
                      <div className="mb-8">
                        <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">Order Details</h3>
                        <div className="overflow-hidden border border-gray-200 rounded-lg">
                          <table className="w-full">
                            <thead className="bg-gray-50">
                              <tr>
                                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-700">Description</th>
                                <th className="px-4 py-3 text-right text-sm font-semibold text-gray-700">Amount</th>
                              </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-200">
                              <tr>
                                <td className="px-4 py-3">
                                  <div>
                                    <p className="font-medium text-gray-900">{orderData.order_title || "Order"}</p>
                                    {orderData.order_description && (
                                      <p className="text-sm text-gray-500 mt-1">{orderData.order_description}</p>
                                    )}
                                  </div>
                                </td>
                                <td className="px-4 py-3 text-right font-medium text-gray-900">
                                  {formatAmount(subtotal)}
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                      </div>

                      {/* Summary */}
                      <div className="border-t border-gray-200 pt-6">
                        <div className="max-w-xs ml-auto space-y-3">
                          <div className="flex justify-between text-gray-600">
                            <span>Subtotal</span>
                            <span className="font-medium">{formatAmount(subtotal)}</span>
                          </div>
                          <div className="flex justify-between text-gray-600">
                            <span>VAT (7.5%)</span>
                            <span className="font-medium">{formatAmount(vat)}</span>
                          </div>
                          {paidAmount > 0 && (
                            <div className="flex justify-between text-gray-600">
                              <span>Amount Paid</span>
                              <span className="font-medium text-green-600">-{formatAmount(paidAmount)}</span>
                            </div>
                          )}
                          <div className="flex justify-between items-center pt-3 border-t border-gray-200">
                            <span className="font-bold text-gray-900">Total</span>
                            <span className="text-xl font-bold text-gray-900">{formatAmount(balanceDue > 0 ? balanceDue : total)}</span>
                          </div>
                          {balanceDue > 0 && (
                            <div className="flex justify-between items-center pt-2">
                              <span className="text-sm text-gray-500">Balance Due</span>
                              <span className="text-lg font-bold text-amber-600">{formatAmount(balanceDue)}</span>
                            </div>
                          )}
                        </div>
                      </div>

                      {/* Footer */}
                      <div className="mt-8 pt-6 border-t border-gray-200">
                        <div className="flex items-center justify-between text-sm text-gray-500">
                          <div className="flex items-center gap-4">
                            <span className="flex items-center gap-1">
                              <Shield size={14} />
                              Terms & Conditions Apply
                            </span>
                            <span>•</span>
                            <span>Thank you for your business!</span>
                          </div>
                          <div className="text-right">
                            <p className="text-xs">Generated on {formatDateTime(new Date().toISOString())}</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Right Column - Actions & Info */}
                  <div className="space-y-6">
                    {/* Status Card */}
                    <div className="bg-gradient-to-br from-blue-50 to-indigo-50 border border-blue-100 rounded-xl p-5">
                      <h3 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
                        <BarChart size={18} />
                        Invoice Status
                      </h3>
                      <div className="space-y-3">
                        <div className="flex justify-between items-center">
                          <span className="text-gray-600">Payment Status</span>
                          <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                            paymentStatus === "Paid" 
                              ? "bg-emerald-100 text-emerald-800" 
                              : "bg-amber-100 text-amber-800"
                          }`}>
                            {paymentStatus}
                          </span>
                        </div>
                        <div className="flex justify-between items-center">
                          <span className="text-gray-600">Order Status</span>
                          <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                            orderData.order_status === "Completed" 
                              ? "bg-emerald-100 text-emerald-800" 
                              : orderData.order_status === "In Progress"
                              ? "bg-blue-100 text-blue-800"
                              : "bg-amber-100 text-amber-800"
                          }`}>
                            {orderData.order_status || "Pending"}
                          </span>
                        </div>
                        {balanceDue > 0 && (
                          <div className="pt-3 border-t border-blue-100">
                            <p className="text-sm text-gray-600 mb-2">Balance Due</p>
                            <p className="text-2xl font-bold text-gray-900">{formatAmount(balanceDue)}</p>
                            <p className="text-xs text-gray-500 mt-1">Due by {calculateDueDate(orderData.ordered_at || orderData.created_at)}</p>
                          </div>
                        )}
                      </div>
                    </div>

                    {/* Quick Actions */}
                    <div className="border border-gray-200 rounded-xl p-5">
                      <h3 className="font-semibold text-gray-900 mb-4">Quick Actions</h3>
                      <div className="space-y-3">
                        <button
                          onClick={handleDownload}
                          disabled={isGeneratingPDF}
                          className="w-full flex items-center justify-center gap-3 bg-blue-600 text-white px-4 py-3 rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                          {isGeneratingPDF ? (
                            <>
                              <Loader2 size={18} className="animate-spin" />
                              Generating PDF...
                            </>
                          ) : (
                            <>
                              <Download size={18} />
                              Download PDF
                            </>
                          )}
                        </button>
                        <button
                          onClick={() => setShowShareModal(true)}
                          className="w-full flex items-center justify-center gap-3 border border-gray-300 text-gray-700 px-4 py-3 rounded-lg hover:bg-gray-50 transition-colors"
                        >
                          <Share2 size={18} />
                          Share Invoice
                        </button>
                        <button
                          onClick={handlePrint}
                          className="w-full flex items-center justify-center gap-3 border border-gray-300 text-gray-700 px-4 py-3 rounded-lg hover:bg-gray-50 transition-colors"
                        >
                          <Printer size={18} />
                          Print
                        </button>
                      </div>
                    </div>

                    {/* Client Information */}
                    <div className="border border-gray-200 rounded-xl p-5">
                      <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
                        <User size={18} />
                        Client Information
                      </h3>
                      <div className="space-y-3">
                        <div>
                          <p className="text-sm text-gray-500 mb-1">Full Name</p>
                          <p className="font-medium text-gray-900">{orderData.client_full_name || "N/A"}</p>
                        </div>
                        {orderData.client_email && (
                          <div>
                            <p className="text-sm text-gray-500 mb-1">Email</p>
                            <p className="font-medium text-gray-900">{orderData.client_email}</p>
                          </div>
                        )}
                        {orderData.client_phone && (
                          <div>
                            <p className="text-sm text-gray-500 mb-1">Phone</p>
                            <p className="font-medium text-gray-900">{orderData.client_phone}</p>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              ) : activeTab === "details" ? (
                <div className="space-y-6">
                  {/* Details content */}
                </div>
              ) : (
                <div className="space-y-6">
                  {/* Timeline content */}
                </div>
              )}
            </div>

            {/* Footer Actions */}
            <div className="sticky bottom-0 bg-white border-t border-gray-200 px-6 py-4">
              <div className="flex items-center justify-between">
                <div className="text-sm text-gray-600">
                  Last updated: {formatDateTime(orderData.updated_at || orderData.created_at)}
                </div>
                <div className="flex items-center gap-3">
                  <button
                    onClick={onClose}
                    className="px-5 py-2.5 border border-gray-300 text-gray-700 rounded-xl hover:bg-gray-50 transition-colors font-medium"
                  >
                    Close
                  </button>
                  <button
                    onClick={handleDownload}
                    disabled={isGeneratingPDF}
                    className="px-5 py-2.5 bg-gradient-to-r from-blue-600 to-blue-700 text-white rounded-xl hover:from-blue-700 hover:to-blue-800 transition-all shadow-lg font-medium flex items-center gap-2 disabled:opacity-50"
                  >
                    {isGeneratingPDF ? (
                      <>
                        <Loader2 size={18} className="animate-spin" />
                        Generating...
                      </>
                    ) : (
                      <>
                        <Download size={18} />
                        Download Invoice
                      </>
                    )}
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Share Modal */}
      {showShareModal && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md overflow-hidden animate-slideUp">
            <div className="p-6 border-b border-gray-200">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-blue-100 rounded-lg">
                    <Share2 className="text-blue-600" size={20} />
                  </div>
                  <div>
                    <h3 className="font-bold text-gray-900">Share Invoice</h3>
                    <p className="text-sm text-gray-600">Send invoice to client</p>
                  </div>
                </div>
                <button
                  onClick={() => setShowShareModal(false)}
                  className="p-2 hover:bg-gray-100 rounded-lg"
                >
                  <X size={20} className="text-gray-500" />
                </button>
              </div>
            </div>

            <div className="p-6">
              <div className="space-y-3">
                <button
                  onClick={() => shareInvoice("email")}
                  className="w-full flex items-center justify-between p-4 border border-gray-200 rounded-xl hover:bg-gray-50 transition-colors group"
                >
                  <div className="flex items-center gap-3">
                    <div className="p-2 bg-blue-100 rounded-lg group-hover:bg-blue-600 group-hover:text-white transition-colors">
                      <Mail size={20} className="text-blue-600 group-hover:text-white" />
                    </div>
                    <div className="text-left">
                      <p className="font-medium text-gray-900">Email</p>
                      <p className="text-sm text-gray-600">Send as PDF attachment</p>
                    </div>
                  </div>
                  <ChevronRight size={20} className="text-gray-400 group-hover:text-blue-600" />
                </button>

                <button
                  onClick={() => shareInvoice("whatsapp")}
                  className="w-full flex items-center justify-between p-4 border border-gray-200 rounded-xl hover:bg-gray-50 transition-colors group"
                >
                  <div className="flex items-center gap-3">
                    <div className="p-2 bg-green-100 rounded-lg group-hover:bg-green-600 group-hover:text-white transition-colors">
                      <MessageSquare size={20} className="text-green-600 group-hover:text-white" />
                    </div>
                    <div className="text-left">
                      <p className="font-medium text-gray-900">WhatsApp</p>
                      <p className="text-sm text-gray-600">Share via WhatsApp</p>
                    </div>
                  </div>
                  <ChevronRight size={20} className="text-gray-400 group-hover:text-green-600" />
                </button>

                <button
                  onClick={handlePrint}
                  className="w-full flex items-center justify-between p-4 border border-gray-200 rounded-xl hover:bg-gray-50 transition-colors group"
                >
                  <div className="flex items-center gap-3">
                    <div className="p-2 bg-gray-100 rounded-lg group-hover:bg-gray-800 group-hover:text-white transition-colors">
                      <Printer size={20} className="text-gray-600 group-hover:text-white" />
                    </div>
                    <div className="text-left">
                      <p className="font-medium text-gray-900">Print</p>
                      <p className="text-sm text-gray-600">Print physical copy</p>
                    </div>
                  </div>
                  <ChevronRight size={20} className="text-gray-400 group-hover:text-gray-600" />
                </button>
              </div>

              <div className="mt-6 p-4 bg-blue-50 rounded-lg">
                <div className="flex items-start gap-3">
                  <Zap size={18} className="text-blue-600 mt-0.5" />
                  <div>
                    <p className="text-sm font-medium text-blue-900">Quick Tip</p>
                    <p className="text-sm text-blue-700 mt-1">
                      For best results, share the PDF version for professional formatting and easy client access.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      <style>{`
        @keyframes slideIn {
          from {
            opacity: 0;
            transform: translateX(100%);
          }
          to {
            opacity: 1;
            transform: translateX(0);
          }
        }
        @keyframes slideOut {
          from {
            opacity: 1;
            transform: translateX(0);
          }
          to {
            opacity: 0;
            transform: translateX(100%);
          }
        }
        @keyframes slideUp {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
        @keyframes fadeIn {
          from { opacity: 0; }
          to { opacity: 1; }
        }
        .animate-slideIn {
          animation: slideIn 0.3s ease-out;
        }
        .animate-slideOut {
          animation: slideOut 0.3s ease-out;
        }
        .animate-slideUp {
          animation: slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1);
        }
        .animate-fadeIn {
          animation: fadeIn 0.2s ease-out;
        }
      `}</style>
    </>
  );
};

OrderInvoice.propTypes = {
  onClose: PropTypes.func.isRequired,
  order: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.number,
    PropTypes.object,
  ]).isRequired,
};

export default OrderInvoice;